最終課題 : フォロー機能の実装
Shunsuke-Shimura/final-task pull request #5
Opened 2021-03-26 02:24 UTC by Shunsuke-Shimura

フォロー機能を実装しました。
画面では`/accounts/profile/<int:pk>/`からユーザーのプロフィール画面に飛び、そこからフォローとアンフォローができるようになっています。

2021-03-26 12:41 UTC, Akinori13 requested changes
Follow機能、Unfollow機能とProfile機能のViewを分けて実装してください。
その上でいくつかコメントしました。

2021-03-26 12:41 UTC, Akinori13 commented on tmitt3r/templates/tmitt3r/home.html
> +        <p>By : @{{ tm33t.poster.get_username }}</p>
参照先のUserは`__str__`メソッドでusernameを返すので、`tm33.poster`で大丈夫です。
詳しくは、DjangoのUserはAbstractUserを、AbstractUserはAbstractBaseUserを継承しているので、AbstractBaseUserを確認してください。
また他の場所も確認してください。

2021-03-26 12:41 UTC, Akinori13 commented on accounts/views.py
> +        try:
GETで不適切な内容がPOSTされないようにフロントエンドで制約していますが、バックエンドのヴァリデーションもしっかり設定しましょう。

実際に以下の方法でChromeの開発者ツールで確認してみましょう。
1. ID=1のユーザーでログインします。
2. `accounts/profile/2/`にアクセスします。
3. 開発者ツールでformのaction属性を`action="/accounts/profile/1/"`に書き換え、Followボタンをクリックします。
4. 自分自身をフォローできてしまいます。

2021-03-26 12:41 UTC, Akinori13 commented on accounts/views.py
> +        except:
正常に動作した時と例外処理がProfileページに反映されていません。

2021-03-26 12:41 UTC, Akinori13 commented on accounts/views.py
> +        context['latest_tm33t_list'] = Tm33t.objects.filter(poster=self.object).order_by('-post_time')[:10]
ユーザーとツイートは一対多の関係にあるので、`tm33t_set`という形でユーザーの投稿一覧を取得することもできます。

2021-03-26 14:46 UTC, Shunsuke-Shimura commented on tmitt3r/templates/tmitt3r/home.html
> +        <p>By : @{{ tm33t.poster.get_username }}</p>
なるほど！そうだったんですね！
`tm33t.poster`に修正し、他の場所も確認しました。

2021-03-26 14:48 UTC, Shunsuke-Shimura commented on accounts/views.py
> +        context['latest_tm33t_list'] = Tm33t.objects.filter(poster=self.object).order_by('-post_time')[:10]
`Tm33t`モデルの`poster`フィールドに`related_name=tm33ts`を追加して、コンテキストの取得も修正しました。

2021-03-26 14:58 UTC, Shunsuke-Shimura commented on accounts/views.py
> +        try:
確かにそうですね。
実はこの部分がよくわかりませんでした。
できれば`FormView`を使いたかったのですが、それだとGETメソッドの時にフォロー状態をフォームに紐づけることができなくて、、、何かいい方法はありますかね？

2021-03-27 02:43 UTC, Akinori13 commented on accounts/views.py
> +        try:
`UserDetailView`：ユーザ情報（フォロー数とフォロワー数、過去の投稿など）を表示する機能、テンプレートは`profile.html`
`FollowView`：フォロー機能、テンプレートは`follow.html`
`UnFollowView`：フォロー解除機能、テンプレートは`unfollow.html`
の３つに分けましょう。

2021-03-27 09:23 UTC, Shunsuke-Shimura commented on accounts/views.py
> +        try:
了解しました。
3つのビューに分けて実装しました。再度レビューをよろしくお願いします。

2021-03-27 14:51 UTC, Akinori13 requested changes
いくつかコメントしました。

2021-03-27 14:51 UTC, Akinori13 commented on accounts/views.py
> +class FollowView(FormView):
ログインしてない人も見れてしまいます。

2021-03-27 14:51 UTC, Akinori13 commented on accounts/views.py
> +class UnfollowView(FormView):
ログインしてない人も見れてしまいます。

2021-03-27 14:51 UTC, Akinori13 commented on accounts/views.py
> +            Follows.objects.filter(actor=self.request.user, followed_user=self.tar_user).delete()
ここは`get`で大丈夫です。

2021-03-27 14:51 UTC, Akinori13 commented on accounts/views.py
> +            except:
ここの例外処理は複合ユニーク制約に対するものなので、事前にチェックして分岐させましょう。

2021-03-27 14:51 UTC, Akinori13 commented on accounts/views.py
> +        if self.request.user == self.tar_user:
（`form.add_error(field_name, message)`でエラーメッセージを伝えられます。）

2021-03-27 14:51 UTC, Akinori13 commented on accounts/views.py
> +        self.tar_user = User.objects.get(username=username)
`tar`をより分かりやすく命名しましょう。

2021-03-27 14:51 UTC, Akinori13 commented on accounts/views.py
> +            Follows.objects.filter(actor=self.request.user, followed_user=self.tar_user).delete()
ごめんなさい。`filter`を使った意図を見落として、さらに浅はかに考えてしまいました。
`get_object_or_404()`を使いましょう（もしくは例外処理）。`tar_user`をフォローしていない状態で、フォロー解除を試みると`User.DoesNotExist`のエラーが発生します。[参考](https://docs.djangoproject.com/en/3.1/topics/http/shortcuts/)

2021-03-27 14:51 UTC, Akinori13 commented on accounts/templates/accounts/profile.html
> +    <p>following state : {{ following_state|capfirst }}</p>
今回は`username`でフォロー機能を実装していますが、ユーザーが該当機能を使いやすいように、profile.htmlに
```html
// profiled_userがrequest.userでない場合
// 自分がフォローしている場合に表示
<a href="{% url 'accounts:follow' profiled_user.id %}">
// 自分がフォローしていない場合に表示
<a href="{% url 'accountsun:follow' profiled_user.id %}">
```
のように記載することもできます。

2021-03-27 14:51 UTC, Akinori13 commented on accounts/templates/accounts/profile.html
> +    <p>following state : {{ following_state|capfirst }}</p>
大切なことはフロントエンドとバックエンドのバリデーションを一致させることです。
修正前はフロントエンドでprofiled_userがrequest.userでない場合を想定していたにも関わらず、バックエンドではそれがバリデーションできていないから修正をお願いしました。

なお三つのViewに分けてもらったのは、一つのViewに機能をたくさんつけるのはバクの発生の原因になるからです。（もちろんHTTPメソッドで分ける方法などもあります。）
ちなみにプロフィール画面で完結させたい場合はAjaxを使えます。いいね機能の時に使ってみてもよいと思います。

2021-03-28 00:57 UTC, Shunsuke-Shimura commented on accounts/templates/accounts/profile.html
> +    <p>following state : {{ following_state|capfirst }}</p>
なるほど。そういうことだったんですね！
Ajaxも少し調べてみます！

2021-03-28 00:58 UTC, Shunsuke-Shimura commented on accounts/views.py
> +        self.tar_user = User.objects.get(username=username)
`target_user`に修正しました。

2021-03-28 01:05 UTC, Shunsuke-Shimura commented on accounts/views.py
> +        if self.request.user == self.tar_user:
エラーメッセージを追加しました。

2021-03-28 01:06 UTC, Shunsuke-Shimura commented on accounts/views.py
> +            Follows.objects.filter(actor=self.request.user, followed_user=self.tar_user).delete()
`get_object_or_404()`を使いました。

2021-03-28 01:06 UTC, Shunsuke-Shimura commented on accounts/views.py
> +class FollowView(FormView):
親クラスに`LoginRequiredMixin`を追加しました。

2021-03-28 01:07 UTC, Shunsuke-Shimura commented on accounts/views.py
> +class UnfollowView(FormView):
親クラスに`LoginRequiredMixin`を追加しました。

2021-03-28 07:15 UTC, Akinori13 approved these changes

2021-03-28 07:15 UTC, merged