最終課題 : お気に入り機能の実装
Shunsuke-Shimura/final-task pull request #6
Opened 2021-04-05 06:04 UTC by Shunsuke-Shimura

お気に入り機能を実装しました。
ツイートの詳細画面、またはツイートのリストにあるハートマークを押すことで対象のツイートをお気に入り登録することができます。

2021-04-06 09:29 UTC, kpppn commented on accounts/templates/accounts/profile.html
> +    {% include 'tmitt3r/tm33t_list.html' %}
```suggestion
    {% include 'tmitt3r/tm33t_list.html' with name=user %}
```

2021-04-06 09:30 UTC, kpppn commented on accounts/views.py
> +        context['name'] = str(self.object)
この行いらない

2021-04-06 09:35 UTC, kpppn commented on tmitt3r/models.py
> +        else:
elseいらない

2021-04-06 09:48 UTC, kpppn commented on tmitt3r/static/tmitt3r/js/like_ajax.js
> +    } else {
if ブロックでreturnすればelse不要

2021-04-06 09:52 UTC, kpppn commented on tmitt3r/static/tmitt3r/js/like_ajax.js
> +    if (document.cookie && document.cookie !== '') {
```suggestion
    if (!document.cookie || document.cookie == '') {
        return cookieValue
    }
```

2021-04-06 09:54 UTC, kpppn commented on tmitt3r/views.py
> +    def get_context_data(self, **kwargs):
context return忘れ

2021-04-06 09:59 UTC, kpppn commented on tmitt3r/views.py
> +        context['name'] = 'You'
view 側でログインしているユーザーと投稿しているユーザーを比較してあげるとよいかも

2021-04-06 10:04 UTC, kpppn requested changes
確認ください

2021-04-07 11:52 UTC, Shunsuke-Shimura commented on accounts/templates/accounts/profile.html
> +    {% include 'tmitt3r/tm33t_list.html' %}
`with name=profiled_user`を渡すように修正しました。

2021-04-07 11:53 UTC, Shunsuke-Shimura commented on accounts/views.py
> +        context['name'] = str(self.object)
対象の行を削除しました。

2021-04-07 11:53 UTC, Shunsuke-Shimura commented on tmitt3r/models.py
> +        else:
else文のみを削除しました。

2021-04-07 11:54 UTC, Shunsuke-Shimura commented on tmitt3r/static/tmitt3r/js/like_ajax.js
> +    } else {
`return`で返して`else`を削除しました。

2021-04-07 11:54 UTC, Shunsuke-Shimura commented on tmitt3r/static/tmitt3r/js/like_ajax.js
> +    if (document.cookie && document.cookie !== '') {
提案のように修正しました。

2021-04-07 11:56 UTC, Shunsuke-Shimura commented on tmitt3r/views.py
> +    def get_context_data(self, **kwargs):
contextのtm33tオブジェクトを更新してcontextを返すように修正しました。

2021-04-07 12:04 UTC, Shunsuke-Shimura commented on tmitt3r/views.py
> +        context['name'] = 'You'
view側でユーザーを比較するように修正しました。

2021-04-08 14:51 UTC, merged